import { ValueType } from 'realgrid';

export const Config = [
  {
    fieldName: 'edu_year',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '기준년도',
    width: 105,
  },
  {
    fieldName: 'dept_code',
    dataType: ValueType.TEXT,
    visible: false,
    headerText: '부서코드',
    width: 80,
  },
  {
    fieldName: 'dept_name',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '부서명',
    width: 130,
  },
  {
    fieldName: 'emp_no',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '사번',
    width: 105,
  },
  {
    fieldName: 'emp_name',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '성명',
    width: 110,
  },
  {
    fieldName: 'edu_name',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육명',
    width: 250,
  },
  {
    fieldName: 'edu_cost',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육비',
    width: 130,
  },
  {
    fieldName: 'edu_from_dt',
    dataType: ValueType.DATE,
    visible: true,
    headerText: '교육시작일',
    datetimeFormat: 'yyyy-MM-dd',
    width: 110,
  },
  {
    fieldName: 'edu_to_dt',
    dataType: ValueType.DATE,
    visible: true,
    headerText: '교육종료일',
    datetimeFormat: 'yyyy-MM-dd',
    width: 110,
  },
  {
    fieldName: 'edu_time',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육시간',
    width: 110,
  },
  {
    fieldName: 'edu_type_name',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육형태',
    width: 110,
  },
  {
    fieldName: 'edu_large_class_name',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육대분류',
    width: 110,
  },
  {
    fieldName: 'edu_middle_class_name',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육중분류',
    width: 110,
  },
  {
    fieldName: 'edu_supervision_name',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육주관',
    width: 110,
  },
  {
    fieldName: 'edu_location',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육장소',
    width: 110,
  },
  {
    fieldName: 'edu_rate',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육수료율',
    width: 110,
  },
  {
    fieldName: 'edu_cmplt_yn',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '교육수료여부',
    width: 110,
  },
  {
    fieldName: 'edu_absence_yn',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '불참여부',
    width: 110,
  },
  {
    fieldName: 'rmk',
    dataType: ValueType.TEXT,
    visible: true,
    headerText: '비고',
    width: 110,
  },
  {
    fieldName: 'first_rg_yms',
    dataType: ValueType.TEXT,
    visible: false,
  },
  {
    fieldName: 'first_rg_idf',
    dataType: ValueType.TEXT,
    visible: false,
  },
  {
    fieldName: 'last_update_yms',
    dataType: ValueType.TEXT,
    visible: false,
  },
  {
    fieldName: 'last_update_idf',
    dataType: ValueType.TEXT,
    visible: false,
  },
  {
    fieldName: 'row_stat',
    dataType: ValueType.TEXT,
    visible: false,
  },
];
